import {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Award,
  BarChart,
  Bookmark,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Bug,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Code2,
  Copy,
  Cpu,
  Database,
  Download,
  Edit,
  ExternalLink,
  FileCode,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe,
  GraduationCap,
  Grid3x3,
  Hash,
  Heart,
  Home,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  Package,
  Palette,
  Paperclip,
  Pause,
  PenTool,
  Phone,
  PieChart,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCw,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsUp,
  Trash,
  Trash2,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

import {
  siDevdotto,
  siDiscord,
  siDocker,
  siExpress,
  siFacebook,
  siFigma,
  siGit,
  siGithub,
  siGmail,
  siGraphql,
  siHashnode,
  siHtml5,
  siInstagram,
  siJavascript,
  siLeetcode,
  siLinux,
  siMedium,
  siMongodb,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siPostgresql,
  siPostman,
  siPython,
  siReact,
  siRedis,
  siStackoverflow,
  siTailwindcss,
  siTelegram,
  siTypescript,
  siVercel,
  siWhatsapp,
  siX,
  siYoutube,
  type SimpleIcon,
} from "simple-icons";
import type { CertColor } from "@/models/Certification";

export const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Award,
  BarChart,
  Bookmark,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Bug,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Code2,
  Copy,
  Cpu,
  Database,
  Download,
  Edit,
  ExternalLink,
  FileCode,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe,
  GraduationCap,
  Grid3x3,
  Hash,
  Heart,
  Home,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  Package,
  Palette,
  Paperclip,
  Pause,
  PenTool,
  Phone,
  PieChart,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCw,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  ThumbsUp,
  Trash,
  Trash2,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wrench,
  X,
  Zap,
};

export const brandIconMap: Record<string, SimpleIcon> = {
  devdotto: siDevdotto,
  discord: siDiscord,
  docker: siDocker,
  express: siExpress,
  facebook: siFacebook,
  figma: siFigma,
  git: siGit,
  github: siGithub,
  gmail: siGmail,
  graphql: siGraphql,
  hashnode: siHashnode,
  html5: siHtml5,
  instagram: siInstagram,
  javascript: siJavascript,
  leetcode: siLeetcode,
  linux: siLinux,
  medium: siMedium,
  mongodb: siMongodb,
  nextjs: siNextdotjs,
  nodejs: siNodedotjs,
  npm: siNpm,
  postgresql: siPostgresql,
  postman: siPostman,
  python: siPython,
  react: siReact,
  redis: siRedis,
  stackoverflow: siStackoverflow,
  tailwindcss: siTailwindcss,
  telegram: siTelegram,
  typescript: siTypescript,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  twitter: siX,
  x: siX,
  youtube: siYoutube,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Circle;
}

function normaliseBrandName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[.\-+\s]/g, "");
}

export function getBrandIcon(name: string): SimpleIcon | null {
  const key = normaliseBrandName(name);
  return brandIconMap[key] ?? null;
}

// Token-derived, not raw palette classes, so these follow the active theme.
// chart-2/4/5 are reused for warning/info/success since they're already
// tuned as a readable, distinguishable series (see app/globals.css).
export const certColorMap: Record<
  CertColor,
  { bg: string; text: string; border: string }
> = {
  primary: {
    bg: "bg-primary/10",
    text: "text-primary",
    border: "border-primary/20",
  },
  accent: {
    bg: "bg-accent",
    text: "text-accent-foreground",
    border: "border-accent-foreground/20",
  },
  success: {
    bg: "bg-chart-5/10",
    text: "text-chart-5",
    border: "border-chart-5/20",
  },
  warning: {
    bg: "bg-chart-2/10",
    text: "text-chart-2",
    border: "border-chart-2/20",
  },
  info: {
    bg: "bg-chart-4/10",
    text: "text-chart-4",
    border: "border-chart-4/20",
  },
  neutral: {
    bg: "bg-muted",
    text: "text-muted-foreground",
    border: "border-border",
  },
};
